
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhxrnvnawtviozxnvqks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoeHJudm5hd3R2aW96eG52cWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjgxNTMsImV4cCI6MjA2MTI0NDE1M30.ViVzlcSSj3a_bpxy7lEJeqaE5OA2kMuK7x-kM0nBKs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});
